version: "3"
services:
  tristanv2:
    image: tristan-v2
    container_name: trv2
    build:
      context: .
      args:
        USERNAME: $USER
    volumes:
      - type: bind
        source: ../
        target: /home/$USER/tristan-v2
